title: cullenhgn
description: wannabe coder
author: Cullen Hogan
github: https://github.com/cullenhgn
about: Just my little slice of the web to try and keep track of tinkering around with mostly Python.
disqus_shortname: cullenhgn
google_analytics: ""

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/cullenhgn"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: cullenhgn
  fb_appid: ""

urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/cullenhgn
    - text: XML Feed
      url: /feed.xml

url: "https://cullenhgn.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist